### ISSUE TITLE
general features

### ISSUE THREAD

**Issue by pshihn** [pshihn/every-color-picker#1]
Attributes for 
- value
- mode 

Props for 
hsl, rgb, hex

Figure out sizing options

Styling

**Comment by pshihn** [comment]
Thumb colors consistency

Dragging on the thumb when thumb not on canvas

**Comment by justingolden21** [comment]
Just wanna comment here and say this project is super underrated / unnoticed at 37 stars... It's incredibly easy to start using, has lots of features, and looks awesome. Looking forward to using this : )

**Comment by justingolden21** [comment]
Also you misspelled "svelte" in all of your pages : )
